# Generated by Django 5.2.3 on 2025-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('duracion', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('imagen', models.ImageField(upload_to='cursos/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
