# Generated by Django 5.2.3 on 2025-07-01 20:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_alter_curso_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción de la actividad'),
        ),
    ]
