# Generated by Django 5.2.3 on 2025-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['curso', 'clave'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='clave',
            field=models.CharField(max_length=10, unique=True, verbose_name='Clave de la actividad'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], default=1, verbose_name='Nivel'),
        ),
    ]
