# Generated by Django 5.2.3 on 2025-07-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_actividad_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='duracion',
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen'),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
